name: temple_app
description: A temple management system app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_blue: ^0.8.0
  shared_preferences: ^2.0.18
  permission_handler: ^10.2.0
  intl: ^0.18.0
  fl_chart: ^0.62.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true